- ignore:
    name: Use section

- ignore:
    name: Avoid lambda using `infix`

- ignore:
    name: Use <=<

- ignore:
    name: Use record patterns

- ignore:
    name: Use &&

- ignore:
    name: Use <$>
